---
router_id: 10.20.30.1
networks:
  - network: 10.20.30.0
    inverse_mask: 0.0.0.255
    area: 0
  - network: 10.20.40.0
    inverse_mask: 0.0.0.255
    area: 0
  - network: 10.20.50.0
    inverse_mask: 0.0.0.255
    area: 2
dns_servers:
  - 1.1.1.1
  - 8.8.8.8